import time
timestamp = time.strftime('%H:%M:%S')
print(timestamp)
timestamp = time.strftime('%d-%m-%Y, %H:%M:%S,  %z, %a, %A')
print(timestamp)
timestamp = time.strftime('%d-%b-%Y %A, %I:%M:%S %p')
print(timestamp)
timestamp = time.strftime('%c')
print(timestamp)
# timestamp = time.strftime('%H')
# print(timestamp)
# timestamp = time.strftime('%M')
# print(timestamp)
# timestamp = time.strftime('%S')
# print(timestamp)
# https://docs.python.org/3/library/time.html#time.strftime
